### PR TITLE
build libraries

### PR DESCRIPTION
**Pull request by ngam**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ngam** [comment]
This is the build script available in build.sh. We have issues ranging from weird compiler errors for linux, to cross-compile issues for macos, and finally python-related issues in osx. 

The idea is to streamline the build process here:

- First, build the libraries and install them (`cmake ..`, `cmake --build .` and `cmake install .`): this results in having the binaries and libraries installed in $PREFIX/bin and $PREFIX/lib. One caveat here is that `pylibvw` gets installed in `site-packages` (`$SP_DIR`) as intended.
- Second, we build the python package which goes into `site-packages` (we remove building the extension again from setup.py because well, it is already built and installed --- `sed -i.bak '/\"build\_ext\"/d' setup.py`).

This setup works perfectly locally for me (not in the conda-forge setup). I am out of ideas about potential fixes from the build perspective for linux, cross-compile, and osx --- I guess we could just keep trying and see if we could catch something. For the purpose of the python package itself, we really don't have to bother with changing anything since it is a pretty good process. This mess only comes up if we are to do expand this package to include all binaries and libraries. 

Copying @jackgerrits.

```bash
#!/bin/env bash

# Get an updated config.sub and config.guess
cp $BUILD_PREFIX/share/gnuconfig/config.* .

# get the proper ext_suffix:
EXT_NAME_DIRTY="$(python -m sysconfig | grep "EXT_SUFFIX =")"
EXT_NAME_CLEAN=${EXT_NAME_DIRTY:15:200}
EXT_NAME=${EXT_NAME_CLEAN%?}

# get the python inc dir
PYTHON_INC_PATH_EDIT=$(python -c "from distutils.sysconfig import get_python_inc; print(get_python_inc())")

# make a build dir
rm -rf build; mkdir build; cd build

# flatbuffers seems to cause a problem, not sure why?
# need pyver with dot formatted

cmake .. \
          -DRAPIDJSON_SYS_DEP=ON \
          -DFMT_SYS_DEP=ON \
          -DSPDLOG_SYS_DEP=ON \
          -DBUILD_FLATBUFFERS=Off \
          -DBUILD_PYTHON=On \
          -DPY_VERSION="${CONDA_PY:0:1}.${CONDA_PY:1:2}" \
          -DCMAKE_INSTALL_PREFIX=$PREFIX \
          -DBUILD_TESTS=Off \
          -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=$SP_DIR \
          -DCMAKE_PREFIX_PATH=$CONDA_PREFIX \
          -DBoost_NO_BOOST_CMAKE=ON \
          -DVW_PYTHON_SHARED_LIB_SUFFIX=$EXT_NAME \
          -DPython_INCLUDE_DIR=$PYTHON_INC_PATH_EDIT \
          $CMAKE_ARGS

cmake --build . -j${CPU_COUNT}
cmake --install .

cd ..

# since the pylibvw library has been installed already
# don't try to reinstall it again
sed -i.bak '/\"build\_ext\"/d' setup.py

$PYTHON setup.py install

```

**Comment by jackgerrits** [comment]
I am not really sure what the issues are here, I haven't seen them before as far as I can tell. We have CI in the main repo but it does not cover the same diverse set of environments being tested here it seems.

**Comment by ngam** [comment]
> I am not really sure what the issues are here, I haven't seen them before as far as I can tell. We have CI in the main repo but it does not cover the same diverse set of environments being tested here it seems.

Let's revisit in a few weeks. Now that we pushed all submodules really ahead, it could be a matter of time for relevant pieces in conda-forge to catch up. I believe, however, that the same issues happen even if we turn off `SYS_DEP` flags (i.e. using submodules). If I were to guess, I would think it would be some compiler issue or missing little pieces somewhere in the basic units of conda-forge. However, your situation is relatively unique in the way the libraries/binaries are set up (at least in my newbish perspective) and there was a bit of trouble getting things to work on brew (speaking of that, `brew install vowpal-wabbit --HEAD` broke again; however the 9.0.1 version is stable and functioning well).

At some point (depending on the level of investment in vw upstream and availability of maintainers), it may be worthwhile to dig deeper into the libraries and organize / revamp the build process. For now it seems fragmented --- for example, it is weird that building pylibvw requires vw but then we are not shipping it explicitly as well. However, as I said above, for the purpose of a python package, this feedstock is totally fine. We should try to run more tests at some point though (run_tests.py wouldn't work since it requires vw-bin and spanning_tree)

**Comment by jackgerrits** [comment]
> (speaking of that, brew install vowpal-wabbit --HEAD broke again; however the 9.0.1 version is stable and functioning well).

Yep, I am waiting on approval to port [a fix](https://github.com/VowpalWabbit/vowpal_wabbit/commit/57e8ff252a8b790d14acdb7867ba25b55f3b6d26) to master for some older compilers.

I am totally open to suggestions about how to improve the build process. This project has grown over time and we've been trying to smooth out the build process for some time. But as you can see its still a bit complicated.

**Comment by ngam** [comment]
> Yep, I am waiting on approval to port [a fix](https://github.com/VowpalWabbit/vowpal_wabbit/commit/57e8ff252a8b790d14acdb7867ba25b55f3b6d26) to master for some older compilers

Oh, I didn't realize you only applied to the v9.0.1! Sneaky 😆

**Comment by jackgerrits** [comment]
I was trying so hard to get that 9.0.1 patch working and that build break really surprised me. We don't build with GCC 5 in master anymore!

**Pull request closed without merging**
