### PR TITLE
fixing extension

### PR DESCRIPTION
**Pull request by ngam**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by ngam** [comment]
@jackgerrits, so the issue here is the following as @isuruf kindly explained to me in https://github.com/conda-forge/pypy-meta-feedstock/issues/21:

vw compiles a binary library pylibvw and forces it to have an extension .so on unix (even macos). This is fine for regular python (cpython) but pypy expects a totally different extension, but that is, I believe, overridden in your setup.py and CMakeLists. I made some symlinks and they worked fine for linux64 and osx64, but they didn't work for aarch64 and ppc64le as I don't really know what exactly the extension would be for those platforms on top of my head (just guessing below). 

isuruf suggested a patch instead of symlinks, but since you're an active maintainer (maybe the most active?!) upstream, we should discuss this with you here. What do you think we should do?

```
     # these symlink are needed because pypy expects a specific .so
     # upstream hardcodes the .so extension
     # see https://github.com/conda-forge/pypy-meta-feedstock/issues/21
     - ln -s $SP_DIR/pylibvw.so $SP_DIR/pylibvw.pypy37-pp73-x86_64-linux-gnu.so  # [python_impl == 'pypy' and (linux and x86_64)]
     - ln -s $SP_DIR/pylibvw.so $SP_DIR/pylibvw.pypy37-pp73-aarch64-linux-gnu.so  # [python_impl == 'pypy' and (linux and aarch64)]
     - ln -s $SP_DIR/pylibvw.so $SP_DIR/pylibvw.pypy37-pp73-ppc64le-linux-gnu.so  # [python_impl == 'pypy' and (linux and ppc64le)]
     - ln -s $SP_DIR/pylibvw.so $SP_DIR/pylibvw.pypy37-pp73-darwin.so  # [python_impl == 'pypy' and (osx and x86_64)]

```

--- 

Also, I can successfully compile the vw library (not pylibvw) and spanning_tree locally with system deps (spdlog, fmt, rapidjson --- we have all in conda-forge). However, I am a little confused about the need to have exact pinning as per the ext_libs/ext_libs.cmake file. We can patch that here and we can expand the testing. Note, we have global pinning for all three deps and I think that could be a guideline for your pinning. Anyway, I am bringing this up because I believe we could address all these build-related issues in tandem, not separately, #46. I am happy to dig a little deeper for a solution and I can maybe assist with some PRs upstream related to the build, or maybe we could just address these concerns for conda-forge only.

In my head, we should do the following in order:

1. compile the three libraries (targets): vw, spanning_tree, pylibvw (call this output libvowpalwabbit
2. use conda-forge deps for everything (don't vendor anything)
3. install the libraries in $PREFIX/bin (vw and spanning_tree) and $PREFIX/lib (pylibvw) as appropriate
4. build the python package as no arch (call this output pyvowpalwabbit)
5. make a separate output (call it vowpalwabbit) that will combined both libvowpalwabbit and pyvowpalwabbit.

This way install vowpalwabbit will have both the command-line utilities as well as the python package.

Note: currently, even if with vendoring spdlog, fmt, and rapidjson, they don't actually get vendored with the python package --- they're simply built again. If I understand correctly, the only artifact besides the python package is pylibvw.so.

**Comment by ngam** [comment]
Pinging @xhochy and @isuruf if available for advice on any of the above.

**Comment by jackgerrits** [comment]
I'd be more than happy to do the upstream change of fixing the extension. My thinking for that would be for `setup.py` to communicate to CMake what the required extension is, similar to the way we specify the required Python version. Do you think that would work?

In the CMake config there are options to allow system dependencies. Generally speaking the default is vendor since that is easier for a user trying to directly build the library but of course system deps are important for packaging. Specifics of system vs vendor consumption of dependencies can be found [here](https://github.com/VowpalWabbit/vowpal_wabbit/wiki/Dependencies#details).

As far as dependency version pinning I would say exact pinning is not required. These few dependencies are quite stable and a vast number of versions should work.

> Note: currently, even if with vendoring spdlog, fmt, and rapidjson, they don't actually get vendored with the python package --- they're simply built again

Can you explain this further? Are they not built into the shared lib?

**Comment by ngam** [comment]
>> Note: currently, even if with vendoring spdlog, fmt, and rapidjson, they don't actually get vendored with the python package --- they're simply built again

> Can you explain this further? Are they not built into the shared lib? In the main repo we use the flag -DDSTATIC_LINK_VW_JAVA=On to statically link in the dependencies into the produced shared lib. (The option name is bad,)

They're definitely built and linked to pylibvw.so. My understanding is that: our concern with these ext_libs usually is that they may clash with someone (or some package) installing fmt and then the ext_libs/fmt and fmt would clash. This simply doesn't happen here as far as I could tell and so we could proceed like this for now. However, I haven't looked at how that might look like if we are to bundle in vw and spanning_tree in this package. Having said, all sorts of confusion can result and so it is usually best to use the conda-forge's libraries that are already available (also quicker build time).

Have a look inside this: https://anaconda.org/conda-forge/vowpalwabbit/9.0.0/download/osx-64/vowpalwabbit-9.0.0-py310h9076ab7_2.tar.bz2 --- you will see no trace of fmt, etc. so I assume they're imbedded inside the pylibvw.so? Btw, the same with your PyPI wheels (if I remember correctly).

**Comment by ngam** [comment]
> Do you think that would work?

Yes, this would work perfectly fine. For now, this little gimmick seems to work:

```yaml
      - EXT_NAME_DIRTY="$(python -m sysconfig | grep "SO =")"
      - EXT_NAME_CLEAN=${EXT_NAME_DIRTY:7:100}
      - EXT_NAME=${EXT_NAME_CLEAN%?}
      - ln -s ${SP_DIR}/pylibvw.so ${SP_DIR}/pylibvw${EXT_NAME}  # [python_impl == 'pypy']
```

**Comment by jackgerrits** [comment]
My understanding is that conda uses the envvar `CONDA_PREFIX` to provide its own dependencies. We check for that in `setup.py` here: https://github.com/VowpalWabbit/vowpal_wabbit/blob/01bdf2c2af3435057702c6c4c3ee070c43293dd2/setup.py#L122

And since we statically link those dependencies they don't need to be copied to the resulting package. Is the issue here then that the conda build is not supplying `-DRAPIDJSON_SYS_DEP=On -DFMT_SYS_DEP=On -DSPDLOG_SYS_DEP=On ` ?

**Comment by ngam** [comment]
> Is the issue here then that the conda build is not supplying `-DRAPIDJSON_SYS_DEP=On -DFMT_SYS_DEP=On -DSPDLOG_SYS_DEP=On ` ?

Well, fmt, spdlog, and rapidjson are not listed as dependencies at all. Also, I don't think the resulting cmake call is providing the sys_deps flags: 

```
cmake -DCMAKE_BUILD_TYPE=Release -DPY_VERSION=3.7 -DBUILD_PYTHON=On -DBUILD_TESTS=Off -DWARNINGS=Off -DBoost_NO_BOOST_CMAKE=ON -DCMAKE_PREFIX_PATH=/home/conda/feedstock_root/build_artifacts/vowpalwabbit_1643485294115/_build_env -DPython_INCLUDE_DIR=/home/conda/feedstock_root/build_artifacts/vowpalwabbit_1643485294115/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/include -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/conda/feedstock_root/build_artifacts/vowpalwabbit_1643485294115/work/build/lib.linux-ppc64le-3.7 /home/conda/feedstock_root/build_artifacts/vowpalwabbit_1643485294115/work
```

At any rate, cmake would likely fail with liberally-provided deps, without loosening the pins in ext_libs/ext_libs.cmake.

**Comment by ngam** [comment]
```python
            cmake_args.append("-DPython_INCLUDE_DIR={}".format(get_python_inc()))
```

This should be appended further I think.

**Comment by isuruf** [comment]
> Yes, this would work perfectly fine. For now, this little gimmick seems to work:

No, that's not correct. `SO` is deprecated. Please use the command I gave.

**Comment by jackgerrits** [comment]
I think the versions specified in `ext_libs/ext_libs.cmake` are minimums. For example the [nix package](https://github.com/NixOS/nixpkgs/blob/nixos-21.11/pkgs/applications/science/machine-learning/vowpal-wabbit/default.nix#L43) uses sys deps of whatever version is in the repo.

> This should be appended further I think.

That is there: https://github.com/VowpalWabbit/vowpal_wabbit/blob/01bdf2c2af3435057702c6c4c3ee070c43293dd2/setup.py#L126

**Comment by ngam** [comment]
> > Yes, this would work perfectly fine. For now, this little gimmick seems to work:
> 
> No, that's not correct. 

The part about "work perfectly fine" is with giving that command through setup.py.

> `SO` is deprecated. Please use the command I gave.

Oops, yeah, sorry I missed that:

```
(test_pypy_old) ngam@mp15:~$ python -m sysconfig
Platform: "macosx-10.7-x86_64"
Python version: "3.7"
Current installation scheme: "pypy"

Paths: 
	data = "/Users/ngam/.Mambaforge-MacOSX-x86_64/envs/test_pypy_old"
	include = "/Users/ngam/.Mambaforge-MacOSX-x86_64/envs/test_pypy_old/include"
	platinclude = "/Users/ngam/.Mambaforge-MacOSX-x86_64/envs/test_pypy_old/include"
	platlib = "/Users/ngam/.Mambaforge-MacOSX-x86_64/envs/test_pypy_old/site-packages"
	platstdlib = "/Users/ngam/.Mambaforge-MacOSX-x86_64/envs/test_pypy_old/lib_pypy"
	purelib = "/Users/ngam/.Mambaforge-MacOSX-x86_64/envs/test_pypy_old/site-packages"
	scripts = "/Users/ngam/.Mambaforge-MacOSX-x86_64/envs/test_pypy_old/bin"
	stdlib = "/Users/ngam/.Mambaforge-MacOSX-x86_64/envs/test_pypy_old/lib_pypy"

Variables: 
	ABIFLAGS = ""
	AR = "ar"
	ARFLAGS = "rc"
	CC = "gcc -pthread -arch x86_64"
	CCSHARED = "-fPIC"
	CFLAGS = "-DNDEBUG -O2"
	CXX = "g++ -pthread -arch x86_64"
	EXE = ""
	EXT_SUFFIX = ".pypy37-pp73-darwin.so"
	GNULD = "yes"
	INCLUDEPY = "/Users/ngam/.Mambaforge-MacOSX-x86_64/envs/test_pypy_old/include"
	LDLIBRARY = "libpypy3-c.dylib"
	LDSHARED = "gcc -pthread -arch x86_64 -shared -undefined dynamic_lookup"
	LDVERSION = "3.7"
	LIBDIR = "/Users/ngam/.Mambaforge-MacOSX-x86_64/envs/test_pypy_old/lib"
	LIBRARY = ""
	MACOSX_DEPLOYMENT_TARGET = "10.7"
	MULTIARCH = "darwin"
	OPT = "-DNDEBUG -O2"
	Py_DEBUG = "0"
	Py_ENABLE_SHARED = "0"
	SHLIB_SUFFIX = ".so"
	SIZEOF_VOID_P = "8"
	SO = ".pypy37-pp73-darwin.so"
	SOABI = "pypy37-pp73"
	VERSION = "3.7"
	abiflags = ""
	base = "/Users/ngam/.Mambaforge-MacOSX-x86_64/envs/test_pypy_old"
	exec_prefix = "/Users/ngam/.Mambaforge-MacOSX-x86_64/envs/test_pypy_old"
	implementation = "PyPy"
	implementation_lower = "pypy"
	installed_base = "/Users/ngam/.Mambaforge-MacOSX-x86_64/envs/test_pypy_old"
	installed_platbase = "/Users/ngam/.Mambaforge-MacOSX-x86_64/envs/test_pypy_old"
	platbase = "/Users/ngam/.Mambaforge-MacOSX-x86_64/envs/test_pypy_old"
	prefix = "/Users/ngam/.Mambaforge-MacOSX-x86_64/envs/test_pypy_old"
	projectbase = "/Users/ngam/.Mambaforge-MacOSX-x86_64/envs/test_pypy_old/bin"
	py_version = "3.7.12"
	py_version_nodot = "37"
	py_version_short = "3.7"
	srcdir = "/Users/ngam/.Mambaforge-MacOSX-x86_64/envs/test_pypy_old/lib_pypy/config-3.7-darwin"
	userbase = "/Users/ngam/.local"
User: 
	data = "/Users/ngam/.local"
	include = "/Users/ngam/.local/include/pypy3.7"
	platlib = "/Users/ngam/.local/lib/pypy3.7/site-packages"
	platstdlib = "/Users/ngam/.local/lib/pypy3.7"
	purelib = "/Users/ngam/.local/lib/pypy3.7/site-packages"
	scripts = "/Users/ngam/.local/bin"
	stdlib = "/Users/ngam/.local/lib/pypy3.7"

```

Btw, @isuruf, shouldn't `SHLIB_SUFFIX` be changed above?

**Comment by ngam** [comment]
I will replace `"SO ="` with `"EXT_SUFFIX ="` above.

**Comment by ngam** [comment]
> I think the versions specified in `ext_libs/ext_libs.cmake` are minimums. For example the [nix package](https://github.com/NixOS/nixpkgs/blob/nixos-21.11/pkgs/applications/science/machine-learning/vowpal-wabbit/default.nix#L43) uses sys deps of whatever version is in the nixpkgs repo.
> 
> > This should be appended further I think.
> 
> That is there: https://github.com/VowpalWabbit/vowpal_wabbit/blob/01bdf2c2af3435057702c6c4c3ee070c43293dd2/setup.py#L126

I meant, we should append `-DRAPIDJSON_SYS_DEP=On -DFMT_SYS_DEP=On -DSPDLOG_SYS_DEP=On` as well.

**Comment by isuruf** [comment]
> Btw, @isuruf, shouldn't SHLIB_SUFFIX be changed above?

No, why do you think it needs to be changed?

**Comment by ngam** [comment]
> > Btw, @isuruf, shouldn't SHLIB_SUFFIX be changed above?
> 
> No, why do you think it needs to be changed?

This exact problem we are facing? That PyPI is expecting a modified `.<something>.so` instead of `.so`

**Comment by jackgerrits** [comment]
> > I think the versions specified in `ext_libs/ext_libs.cmake` are minimums. For example the [nix package](https://github.com/NixOS/nixpkgs/blob/nixos-21.11/pkgs/applications/science/machine-learning/vowpal-wabbit/default.nix#L43) uses sys deps of whatever version is in the nixpkgs repo.
> > > This should be appended further I think.
> > 
> > 
> > That is there: https://github.com/VowpalWabbit/vowpal_wabbit/blob/01bdf2c2af3435057702c6c4c3ee070c43293dd2/setup.py#L126
> 
> I meant, we should append `-DRAPIDJSON_SYS_DEP=On -DFMT_SYS_DEP=On -DSPDLOG_SYS_DEP=On` as well.

Yes, I agree. That should happen in this recipe though. We don't want to force all users to use sys deps if they are just trying to build from source locally.

**Comment by isuruf** [comment]
> This exact problem we are facing? That pypy is expecting a modified .<something>.so instead of .so

EXT_SUFFIX and SHLIB_SUFFIX are two totally different things.

**Comment by ngam** [comment]
Also, we often do the testing with `test -f "${PREFIX}/lib/libopenlibm${SHLIB_EXT}" `, right? https://github.com/conda-forge/openlibm-feedstock/blob/b13ac0ddf8f231e53ce723cb22e35c9c6d053349/recipe/meta.yaml#L34

Or are SHLIB_EXT and SHLIB_SUFFIX completely unrelated as well?

**Comment by ngam** [comment]
> Yes, I agree. That should happen in this recipe though. We don't want to force all users to use sys deps if they are just trying to build from source locally.

Sorry, we are crossing convos --- but this wouldn't actually force the users, I believe. It would simply attempt `find(pkg)` if this flag is on. If the pkg isn't there, it would build it; if the version is wrong it would fail though. But I am not sure.... https://github.com/VowpalWabbit/vowpal_wabbit/blob/01bdf2c2af3435057702c6c4c3ee070c43293dd2/ext_libs/ext_libs.cmake#L4-L12

**Comment by isuruf** [comment]
Exactly. `SHLIB_SUFFIX` and `SHLIB_EXT` are the same.

**Comment by ngam** [comment]
> Exactly. `SHLIB_SUFFIX` and `SHLIB_EXT` are the same.

Okay, makes sense! Thank for taking the time to explain all of this; I would have been completely lost without you!

**Comment by ngam** [comment]
> > Exactly. `SHLIB_SUFFIX` and `SHLIB_EXT` are the same.
> 
> Okay, makes sense! Thank for taking the time to explain all of this; I would have been completely lost without you!

Wait... so this means this wouldn't work `test -f "${PREFIX}/lib/libopenlibm${SHLIB_EXT}"` if we build the pypy extensions only??

**Comment by isuruf** [comment]
> Wait... so this means this wouldn't work test -f "${PREFIX}/lib/libopenlibm${SHLIB_EXT}" if we build the pypy extensions only??

I don't understand what you are asking here. `libopenlibm` in your example is not a python extension. It's a regular shared library.
Python extensions are in `site-packages`.

**Comment by ngam** [comment]
Let me phrase it more accurately: if I do `test -f "${SP_DIR}pylibvw${SHLIB_EXT}"` in this case, it would only check for `${SP_DIR}pylibvw.so` and not for `${SP_DIR}pylibvw.pypy37-pp73-darwin.so` even if I am building for pypy, correct?

Hence, my suggestion to perhaps change that, because in my mind that was the only already-exposed variable we have for extensions. Or are there more environment variables exposed carrying such signatures? Thus, my clumsy attempt with `EXT_NAME_DIRTY="$(python -m sysconfig | grep "EXT_SUFFIX =")"` based on your suggestion earlier to make an env variable and do symlinks with it.

**Comment by ngam** [comment]
I understand, long-term we need to have a fix (via patch or upstream) in setup.py/CMakeLists...

**Comment by isuruf** [comment]
> Let me phrase it more accurately: if I do test -f "${SP_DIR}pylibvw${SHLIB_EXT}" in this case, it would only check for ${SP_DIR}pylibvw.so and not for ${SP_DIR}pylibvw.pypy37-pp73-darwin.so even if I am building for pypy, correct?

Yes, but why would you want to do such a test in the first place? It's unnecessary. We don't do `test -f` tests for python extensions. Just normal shared libraries.

> Hence, my suggestion to perhaps change that, because in my mind that was the only already-exposed variable we have for extensions.

No, that variable is not for extensions. Just normal shared libraries

> Thus, my clumsy attempt with EXT_NAME_DIRTY="$(python -m sysconfig | grep "EXT_SUFFIX =")" based on your suggestion earlier to make an env variable and do symlinks with it.

What? I never suggested either.

**Comment by ngam** [comment]
> > Let me phrase it more accurately: if I do test -f "${SP_DIR}pylibvw${SHLIB_EXT}" in this case, it would only check for ${SP_DIR}pylibvw.so and not for ${SP_DIR}pylibvw.pypy37-pp73-darwin.so even if I am building for pypy, correct?
> 
> Yes, but why would you want to do such a test in the first place? It's unnecessary. We don't do `test -f` tests for python extensions. Just normal shared libraries.
> 
> > Hence, my suggestion to perhaps change that, because in my mind that was the only already-exposed variable we have for extensions.
> 
> No, that variable is not for extensions. Just normal shared libraries
> 
> > Thus, my clumsy attempt with EXT_NAME_DIRTY="$(python -m sysconfig | grep "EXT_SUFFIX =")" based on your suggestion earlier to make an env variable and do symlinks with it.
> 
> What? I never suggested either.

LOL, no no. You suggested the `sysconfig` route to see what extension is required, that's what I meant (https://github.com/conda-forge/pypy-meta-feedstock/issues/21#issuecomment-1024796517)

**Comment by ngam** [comment]
(btw @isuruf I hope it is clear to you that I have little idea what the difference between an extension and shared library is --- I am learning all of this step by step and I really appreciate your patience in explaining the stuff!)

**Pull request merged**
