### PR TITLE
use sys deps + build libs

### PR DESCRIPTION
**Pull request by ngam**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jackgerrits** [comment]
Here is the current release candidate: https://github.com/VowpalWabbit/vowpal_wabbit/tree/releases/9.0.1

**Comment by ngam** [comment]
> Here is the current release candidate: https://github.com/VowpalWabbit/vowpal_wabbit/tree/releases/9.0.1

Thanks, here I am trying to slip down the deps for the python package. I see you have no deps on pypi (meaning, your package kinda puts everything it needs in the pylibvw --- is that accurate?)

**Comment by ngam** [comment]
> Here is the current release candidate: https://github.com/VowpalWabbit/vowpal_wabbit/tree/releases/9.0.1

Btw, let's see when the bots gets to it ;)

**Comment by jackgerrits** [comment]
Would you like me to wait to actually make the release in case you need further changes?

**Comment by ngam** [comment]
I think you could make a tag (not necessarily a release) so that bots can pick it up. We are in no hurry here since we are not building the vw-bin stuff yet, but for homebrew it may need a release, idk (I don't really do anything with homebrew myself)

**Comment by jackgerrits** [comment]
Once I tag I may as well release I think. I was just asking is there anything from your end that should stop me tagging 9.0.1 with that branch?

**Comment by ngam** [comment]
> Once I tag I may as well release I think. I was just asking is there anything from your end that should stop me tagging 9.0.1 with that branch?

Oh, sorry, nothing at all! This branch here (dev) is just building anything. Once you tag/release, the bot will bring it to the master branch in a PR

**Comment by ngam** [comment]
@jackgerrits 

any idea what might be causing `error: 'formatbuf' was not declared in this scope; did you mean 'format_buf'?` in: 

```
[ 97%] Building CXX object vowpalwabbit/CMakeFiles/vw.dir/parser/flatbuffer/parse_label.cc.o
[ 98%] Linking CXX static library libvw.a
[ 98%] Built target vw
[ 98%] Building CXX object python/CMakeFiles/pylibvw.dir/pylibvw.cc.o
In file included from /home/conda/feedstock_root/build_artifacts/vowpalwabbit_1643747406757/work/vowpalwabbit/io/logger.h:28,
                 from /home/conda/feedstock_root/build_artifacts/vowpalwabbit_1643747406757/work/vowpalwabbit/loss_functions.h:8,
                 from /home/conda/feedstock_root/build_artifacts/vowpalwabbit_1643747406757/work/vowpalwabbit/global_data.h:36,
                 from /home/conda/feedstock_root/build_artifacts/vowpalwabbit_1643747406757/work/vowpalwabbit/vw.h:29,
                 from /home/conda/feedstock_root/build_artifacts/vowpalwabbit_1643747406757/work/python/pylibvw.cc:5:
/home/conda/feedstock_root/build_artifacts/vowpalwabbit_1643747406757/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/include/fmt/ostream.h: In function 'void fmt::v8::detail::format_value(fmt::v8::detail::buffer<T>&, const T&, fmt::v8::detail::locale_ref)':
/home/conda/feedstock_root/build_artifacts/vowpalwabbit_1643747406757/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/include/fmt/ostream.h:72:23: error: 'formatbuf' was not declared in this scope; did you mean 'format_buf'?
   72 |   auto&& format_buf = formatbuf<std::basic_streambuf<Char>>(buf);
      |                       ^~~~~~~~~
      |                       format_buf
/home/conda/feedstock_root/build_artifacts/vowpalwabbit_1643747406757/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/include/fmt/ostream.h:72:58: error: expected primary-expression before '>' token
   72 |   auto&& format_buf = formatbuf<std::basic_streambuf<Char>>(buf);
      |                                                          ^~
In file included from /home/conda/feedstock_root/build_artifacts/vowpalwabbit_1643747406757/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/include/boost/smart_ptr/detail/sp_thread_sleep.hpp:22,
                 from /home/conda/feedstock_root/build_artifacts/vowpalwabbit_1643747406757/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/include/boost/smart_ptr/detail/yield_k.hpp:23,
                 from /home/conda/feedstock_root/build_artifacts/vowpalwabbit_1643747406757/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/include/boost/smart_ptr/detail/spinlock_gcc_atomic.hpp:14,
                 from /home/conda/feedstock_root/build_artifacts/vowpalwabbit_1643747406757/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/include/boost/smart_ptr/detail/spinlock.hpp:42,
                 from /home/conda/feedstock_root/build_artifacts/vowpalwabbit_1643747406757/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/include/boost/smart_ptr/detail/spinlock_pool.hpp:25,
                 from /home/conda/feedstock_root/build_artifacts/vowpalwabbit_1643747406757/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/include/boost/smart_ptr/shared_ptr.hpp:29,
                 from /home/conda/feedstock_root/build_artifacts/vowpalwabbit_1643747406757/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/include/boost/shared_ptr.hpp:17,
                 from /home/conda/feedstock_root/build_artifacts/vowpalwabbit_1643747406757/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/include/boost/program_options/options_description.hpp:16,
                 from /home/conda/feedstock_root/build_artifacts/vowpalwabbit_1643747406757/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/include/boost/program_options.hpp:15,
                 from /home/conda/feedstock_root/build_artifacts/vowpalwabbit_1643747406757/work/vowpalwabbit/options_boost_po.h:7,
                 from /home/conda/feedstock_root/build_artifacts/vowpalwabbit_1643747406757/work/python/pylibvw.cc:14:
/home/conda/feedstock_root/build_artifacts/vowpalwabbit_1643747406757/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/include/boost/bind.hpp: At global scope:
/home/conda/feedstock_root/build_artifacts/vowpalwabbit_1643747406757/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/include/boost/bind.hpp:36:1: note: #pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.
   36 | BOOST_PRAGMA_MESSAGE(
      | ^~~~~~~~~~~~~~~~~~~~
/home/conda/feedstock_root/build_artifacts/vowpalwabbit_1643747406757/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/include/boost/detail/iterator.hpp:13:1: note: #pragma message: This header is deprecated. Use <iterator> instead.
   13 | BOOST_HEADER_DEPRECATED("<iterator>")
      | ^~~~~~~~~~~~~~~~~~~~~~~
make[3]: *** [python/CMakeFiles/pylibvw.dir/build.make:76: python/CMakeFiles/pylibvw.dir/pylibvw.cc.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:663: python/CMakeFiles/pylibvw.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:670: python/CMakeFiles/pylibvw.dir/rule] Error 2
make: *** [Makefile:384: pylibvw] Error 2
error: command '/home/conda/feedstock_root/bui
```

It doesn't happen if building directly --- just our linux64 docker builds

**Comment by jackgerrits** [comment]
I haven't seen that before no. `formatbuf` seems to come from the `format.h` include in `ostream.h`. Is it possible an include path is missing or something? It didn't complain about a missing include though.

**Comment by ngam** [comment]
Let me try some things and see how it goes. 

Stuff works fine if compiling locally with more modern compilers, so that could be it, but I don't know ... we will see

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by ngam** [comment]
Closing this in favor of a new PR to explicitly highlight our current bottlenecks.

**Pull request closed without merging**
