### PR TITLE
trying again with ext_libs

### PR DESCRIPTION
**Pull request by ngam**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by xhochy** [comment]
Please read our blog post on cross-compilation to osx-arm64 before hammering on the CIs.

**Comment by ngam** [comment]
> Please read our blog post on cross-compilation to osx-arm64 before hammering on the CIs.

I have... I am happy to stop trying if you prefer that

**Comment by xhochy** [comment]
From the comments on other PRs, it didn't seem that you knew how the cross-compiling setup works. I suggest to you to do the following things:

* Try to get a local setup working. This will also make it easier to debug.
* Join the Gitter channel at https://gitter.im/conda-forge/conda-forge.github.io, there other volunteers should be able to help you. I currently lack the time but others might be able to help you.

**Comment by ngam** [comment]
Thanks, @xhochy. I don't exactly know how a local build will help (it already builds completely fine natively) --- or do you mean do a cross-compilation build locally using docker, etc.? I will keep thinking and revisit. 

> From the comments on other PRs, it didn't seem that you knew how the cross-compiling setup works.

Not sure which PRs you're referring to, but yes, I am in a steep learning phase and quite eager to help. I haven't use conda before August this year, and really haven't even known about conda-forge and all of this until later September/October... So yes, you're likely right I seem to lack knowledge and maybe I come across annoying af --- but hey, I am learning pretty fast thanks to great people like you 😃 

Closing this for now, so not be distraction from the main issue (the unit opt flags in the other PR)

**Comment by xhochy** [comment]
> Thanks, @xhochy. I don't exactly know how a local build will help (it already builds completely fine natively) --- or do you mean do a cross-compilation build locally using docker, etc.? I will keep thinking and revisit.

You can install an Intel/x86-based `mambaforge` on your M1 and then try to run the build using that. That will then run the build nearly as in CI. The only exception is that CI will fail with `bad CPU type` when it tries to run an ARM binary whereas your local build will pass as it can run them. We have a different problem here, so you should be able to reproduce this.

> Not sure which PRs you're referring to, but yes, I am in a steep learning phase and quite eager to help. I haven't used conda before August this year, and really haven't even known about conda-forge and all of this until later September/October (fwiw, I have a PhD in modeling in chemical engineering)... So yes, you're likely right I seem to lack knowledge and maybe I come across annoying af --- but hey, I am learning pretty fast thanks to great people like you 😃

Yes, that's why you should definitely join the Gitter channel!

**Pull request closed without merging**
