### PR TITLE
Update recipe version to 9.0.0

### PR DESCRIPTION
**Pull request by jackgerrits**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jackgerrits** [comment]
@ngam Do you have any ideas why only two checks are failing?

**Comment by ngam** [comment]
> @ngam Do you have any ideas why only two checks are failing?

no idea, let's troubleshoot. Note, the pypy ones are failing. Let me see what we can do.

**Comment by ngam** [comment]
In both cases, `ModuleNotFoundError: No module named 'pylibvw'`

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by jackgerrits** [comment]
Interesting, Ive never tested on PyPy. Is it possible it doesn't work due to being a native module?

**Comment by ngam** [comment]
> Interesting, Ive never tested on PyPy. Is it possible it doesn't work due to being a native module?

Yes, but let us double check a few things first. We can always disable pypy if that's the case.

**Comment by ngam** [comment]
So, I couldn't `pip install vowpalwabbit` into an env with pypy37...

**Comment by jackgerrits** [comment]
Would that be trying to do a source built or use a binary wheel? The binary wheels target manylinux-2010

**Comment by ngam** [comment]
Because you don't have pypi supported, it would default to build it from the tar.gz files

`mamba create -n test_vw pypy cmake make c-compiler cxx-compiler boost boost-cpp tox zlib`

It actually works. I forgot some of these build deps initially...

**Comment by ngam** [comment]
In the meanwhile, since you're a maintainer upstream, we can skip the pypi build if you'd like the python ones to go out asap. Then we can troubleshoot and fix the pypi build. Let me know what you prefer. If in no hurry, we can try to figure it out and see how far we get over the weekend.

**Comment by ngam** [comment]
> Let me see how far it goes locally; it should be doing almost exactly the same thing as we are doing here.

Okay, I could build it, and I get the same exact error: `ModuleNotFoundError: No module named 'pylibvw'`. Now I will try to see what's breaking down exactly.

**Comment by jackgerrits** [comment]
> In the meanwhile, since you're a maintainer upstream, we can skip the pypi build if you'd like the python ones to go out asap. Then we can troubleshoot and fix the pypi build

Not sure what this means. We have binary wheels uploaded to PyPi for all supported platforms currently. There is no great rush here but I am very unfamiliar with conda so not sure what could be up

**Comment by ngam** [comment]
I am looking currently, and it seems everything is correct --- I can clearly see `pylibvw.so` in both versions under `./site-packages/` but I am not sure if you have changed paths or something recently? It's weird, it should just work.

**Comment by ngam** [comment]
So, here, as you can see: we are building for all these platforms up to python 3.10 as well as pypy3.7. I am saying above, that we can easily skip the pypy3.7 builds since you're not really testing for them upstream.

**Comment by jackgerrits** [comment]
We changed some other package structure but the way pylibvw is imported did not change at all. I am happy to skip pypy3.7 since its not part of the testing matrix in the upstream repo

**Comment by ngam** [comment]
> We changed some other package structure but the way pylibvw is imported did not change at all. I am happy to skip pypy3.7 since its not part of the testing matrix in the upstream repo

Okay, I just confirmed that this same issue existed previously in conda builds:

```
$ conda create -n test_pypy_old pypy vowpalwabbit
$ conda activate test_pypy_old
$ python -c "import pyvw"
...
ModuleNotFoundError: No module named 'pylibvw'
```

I will skip the pypy builds for now and investigate over the weekend. Maybe I will open an issue with the pypy feedstock

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by ngam** [comment]
@jackgerrits, I disabled the pypy builds and opened an issue with the pypy feedstock for advice. This can be merged for now.

**Comment by jackgerrits** [comment]
Thanks so much for your help @ngam! :)

**Comment by ngam** [comment]
No worries, btw, please see #46. I am going to be sending a PR soon with these improvements. It would be good for you to make sure we are doing everything we could do get it right here :) 

I also want to run the whole test suite: run_tests.py --fuzzy_compare

**Comment by jackgerrits** [comment]
I will definitely look. Please @ mention me and I'll be sure to review :)

**Pull request merged**
